name: Tilage
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6170213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6e0ea'
    - '#b6b1b8'
    - '#241e20'
    - '#787379'
    - '#544e50'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
