name: Tilage
favicon: null
layout_spectrum: 0
typography_spectrum: 0.6170213
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010201'
    - '#FFEAE0'
    - '#015465'
    - '#CEBFBD'
    - '#4A7678'
  brandStrength: 1
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.9255319
purpose: []
